services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracleDB1
    restart: unless-stopped
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=nUqzF3J976hz
    volumes:
      - oracle-data:/opt/oracle/oradata # Path for persistent data
volumes:
  oracle-data:

